DRIVER_OBJS= simbuild/micaz/c-sf.o simbuild/micaz/sf.o simbuild/micaz/tossim.o simbuild/micaz/c-support.o simbuild/micaz/sim.o

SFDIR=$(TOSDIR)/lib/tossim/sf

all:
	make micaz sim-sf
	g++ -g -c -o Simulation.o Simulation.cpp -I$(TOSDIR)/lib/tossim -I$(SFDIR)
	g++ -o Simulation $(DRIVER_OBJS)  Simulation.o -lpython2.7
	#mig python -target=null -python-classname=TestSerialMsg TestSerial.h test_serial_msg -o TestSerialMsg.py

clean:
	make clean
	rm -f Simulation Simulation.o
