DRIVER_OBJS= simbuild/micaz/tossim.o simbuild/micaz/c-support.o simbuild/micaz/sim.o


all:
	make micaz sim
	g++ -g -c -o Simulation.o Simulation.cpp -I$(TOSDIR)/lib/tossim
	g++ -o Simulation $(DRIVER_OBJS)  Simulation.o -lpython2.7
	#mig python -target=null -python-classname=TestSerialMsg TestSerial.h test_serial_msg -o TestSerialMsg.py

clean:
	make clean
	rm -f Simulation Simulation.o
